package WebGUI::i18n::Australian::Asset_InOutBoard;

# ABSTRACT: Australian WebGUI (auto) Translation
use strict;
our $I18N = {
    '1' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Status List'
    },
    '1 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'The status list allows you to customise what the \'states\' of a user are. i.e., \'In\' or \'Out\'.'
    },
    '10' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In'
    },
    '11' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Out'
    },
    '12' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Paginate After'
    },
    '12 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'How many rows should be displayed before splitting the results into separate pages? In other words, how many rows should be displayed per page?'
    },
    '13' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Report Template'
    },
    '13 description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Choose a template to display the In/Out Board Report.'
    },
    '14' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Paginate Report After'
    },
    '14 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'Select how many lines you want in each page of the report.  You will be provided links to access additional pages of the report.'
    },
    '15' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Never Checked In'
    },
    '16' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Start Date'
    },
    '16 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'The Start Date can help limit the size of your report by not showing changes in status before the date you select.'
    },
    '17' => {
        'lastUpdated' => 1270751501,
        'message'     => 'End Date'
    },
    '17 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'Like the Start Date, End Date can help limit the size of your report by not showing changes in status after the date you select.'
    },
    '2' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Enter one per line.'
    },
    '20' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board, Template'
    },
    '21' => {
        'lastUpdated' => 1270751501,
        'message'     => '<p>The following variables are made available from In/Out Board:</p>
  '
    },
    '22' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board, Report Template'
    },
    '23' => {
        'lastUpdated' => 1270751501,
        'message'     => '<p>The following variables are available from In/Out Board Report template:</p>
'
    },
    '3' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Who can view reports?'
    },
    '3 description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Which groups are allowed to view reports generated by the In/Out Board Wobject?'
    },
    '4' => {
        'lastUpdated' => 1270751501,
        'message'     => 'View Report'
    },
    '5' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Status'
    },
    '5 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'You may select one status from the list.  If you would like to further explain the reason for the status, use the "What\'s happening" field.'
    },
    '6' => {
        'lastUpdated' => 1270751501,
        'message'     => 'What\'s happening?'
    },
    '6 description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'You can enter in reasons for the change in status (doctor\'s appointment, went home) etc. here.'
    },
    '7' => {
        'lastUpdated' => 1270751501,
        'message'     => 'No Department'
    },
    '8' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Status Log Report'
    },
    'Department' => {
        'context'     => 'label for user profile field',
        'lastUpdated' => 1270751501,
        'message'     => 'Department'
    },
    'HR' => {
        'context'     => 'User profile field, abbreviation for Human Resources',
        'lastUpdated' => 1270751501,
        'message'     => 'HR'
    },
    'IT' => {
        'context'     => 'User profile field, abbreviation for Information Technology',
        'lastUpdated' => 1270751501,
        'message'     => 'IT'
    },
    'In Out Template' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Template'
    },
    'In Out Template description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Choose a template to display the In/Out Board to users.'
    },
    'Regular Staff' => {
        'context'     => 'User profile field',
        'lastUpdated' => 1270751501,
        'message'     => 'Regular Staff'
    },
    'all departments' => {
        'lastUpdated' => 1270751501,
        'message'     => 'All Departments'
    },
    'assetName' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board'
    },
    'canViewReport' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A boolean indicating whether or not the <i>viewReportURL</i> variable will be set.'
    },
    'createdBy' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns which user, either the user himself or a delegate, changed the status for this user.'
    },
    'date label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Date'
    },
    'date.label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized label for the "Date" column of the report.'
    },
    'dateStamp' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A variable that returns the date the status of the user was last updated.'
    },
    'delegate' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Update status for: '
    },
    'delegate description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Select a name from this list to update the status for someone other than yourself.'
    },
    'department' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns the user\'s department. If no department has been assigned to this user, an internationalised label for "No Department" will be used.'
    },
    'deptHasChanged' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A boolean value indicating whether or not this row of data is for a department that is different than the previous rows'
    },
    'displayForm' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A boolean indicating whether or not the <i>form</i> variable will be set.'
    },
    'filter departments' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Filter departments:'
    },
    'filter departments description' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'Each In/Out Board can be configured to serve multiple departments.  By default, all departments are shown in the report.  Select the name of any one department to limit the report to only display status changes from that department.'
    },
    'form' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that contains the HTML for displaying the In/Out Entry Form to update status for the current user or another user.'
    },
    'in out board asset template variables body' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Every asset provides a set of variables to most of its
templates based on the internal asset properties.  Some of these variables may
be useful, others may not.'
    },
    'in out board asset template variables title' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board Asset Template Variables'
    },
    'in/out status delegates' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Status Delegates'
    },
    'in/out status delegates description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Use this form to choose others who can change your status on the In/Out Board.  All users
		who you have already chosen to change your status will be preselected.  To remove a user, deselect them.'
    },
    'in/out status delegates subtext' => {
        'lastUpdated' => 1270751501,
        'message' => 'Multiple users can be selected as delegates.  Delegates will be able to update your status.'
    },
    'inOutGroup' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Who can log in/out?'
    },
    'inOutGroup description' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Which groups are allowed to use this In/Out Board to change their status?'
    },
    'inOutTemplateId' => {
        'lastUpdated' => 1270751501,
        'message'     => 'The ID of the template that is used to display the main screen of the In/Out Board.'
    },
    'message' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns what the user entered in the "What\'s going on?" field when updating their status.'
    },
    'message label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Message'
    },
    'message.label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized label for the "Message" column of the report.'
    },
    'myself' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Myself'
    },
    'paginateAfter' => {
        'lastUpdated' => 1270751501,
        'message'     => 'The number of rows should be displayed per page in the main In/Out Board.'
    },
    'paginateBar' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns the HTML necessary to create a Traditional Pagination Bar.  i.e., &gt;&gt; First, 1, 2, Last &lt;&lt;'
    },
    'report rows_loop' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A loop containing the rows of data for the In/Out Board Report&nbsp;'
    },
    'report title' => {
        'context'     => 'Default i18n label for a In/Out Board Report',
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board Report'
    },
    'report.form' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that contains an HTML form for limiting the scope, by date or department, of the report.'
    },
    'reportTemplateId' => {
        'lastUpdated' => 1270751501,
        'message'     => 'The ID of the template that is used to display In/Out Board reports.'
    },
    'reportTitleLabel' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized title for an In/Out Board Report.'
    },
    'reportViewerGroup' => {
        'lastUpdated' => 1270751501,
        'message'     => 'The ID of the group that is allowed to view reports.'
    },
    'rows_loop' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A loop containing the rows of data for the In/Out Board'
    },
    'select delegate' => {
        'lastUpdated' => 1270751501,
        'message'     => 'In/Out Board, Select Delegates'
    },
    'select delegates label' => {
        'context'     => 'Default i18n label for the URL to select delegates',
        'lastUpdated' => 1270751501,
        'message'     => 'Select Delegates'
    },
    'selectDelegatesLabel' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized title for the URL to select delegates.'
    },
    'selectDelegatesURL' => {
        'lastUpdated' => 1270751501,
        'message'     => 'URL that links to a form where users can select other users (delegates) who
can alter their status.'
    },
    'showReport' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A boolean indicating whether or not the <i>rows_loop</i> variable will be set.'
    },
    'status' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns the user\'s status.  The status of a user is defined by the Status List in the Wobject Properties.  If no status is set for the current user \'Never Checked In\' is returned.'
    },
    'status.label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized label for the "Status" column of the report.'
    },
    'statusList' => {
        'lastUpdated' => 1270751501,
        'message'     => 'A string with all of the possible board statuses separated by newlines.'
    },
    'updatedBy label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Updated By'
    },
    'updatedBy.label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized label for the "Updated By" column of the report.'
    },
    'username' => {
        'lastUpdated' => 1270751501,
        'message' =>
            'A variable that returns the user\'s name.  If the first and last name fields are defined in the user profile, that is what is returned.  Otherwise, the user\'s WebGUI username is returned.  i.e., "John Doe" vs "Jdoe"'
    },
    'username label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Username'
    },
    'username.label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized label for the "Username" column of the report.'
    },
    'view report label' => {
        'lastUpdated' => 1270751501,
        'message'     => 'View Report'
    },
    'viewReportLabel' => {
        'lastUpdated' => 1270751501,
        'message'     => 'Internationalized title for the URL to view reports.'
    },
    'viewReportURL' => {
        'lastUpdated' => 1270751501,
        'message'     => 'URL that links to the view report page.'
    }
};
1;
